"""
Database service for planning/calendar integration.
Tables: users, sessions, session_registrations, user_tokens, graph_sync, ics_feeds, message_log
"""

import psycopg2
import psycopg2.extras
import logging
from typing import Optional, Dict, List
from enum import Enum
from db_config import get_db_config

logger = logging.getLogger(__name__)

DB_CONFIG = get_db_config()


class MessageStatus(Enum):
    RECEIVED = "received"
    PROCESSED = "processed"
    FAILED = "failed"
    DUPLICATE = "duplicate"


def _get_connection():
    try:
        conn = psycopg2.connect(
            host=DB_CONFIG["host"],
            port=int(DB_CONFIG["port"]),
            database=DB_CONFIG["name"],
            user=DB_CONFIG["user"],
            password=DB_CONFIG["password"],
        )
        return conn
    except psycopg2.Error as e:
        logger.error("Database connection failed: %s", e)
        raise


# ============================================================================
# USERS
# master_uuid = official UUID from Identity Service (cross-system)
# user_id     = internal UUID auto-generated by PostgreSQL on insert
# ============================================================================

class UserService:
    @staticmethod
    def save(master_uuid: str, email: str) -> bool:
        """Save a user received from Identity Service (idempotent)."""
        try:
            conn = _get_connection()
            cursor = conn.cursor()
            cursor.execute(
                """
                INSERT INTO users (master_uuid, email)
                VALUES (%s, %s)
                ON CONFLICT (master_uuid) DO UPDATE SET email = EXCLUDED.email
                """,
                (master_uuid, email),
            )
            conn.commit()
            cursor.close()
            conn.close()
            logger.info("User saved | master_uuid=%s | email=%s", master_uuid, email)
            return True
        except psycopg2.Error as e:
            logger.error("UserService.save failed: %s", e)
            return False

    @staticmethod
    def get_by_master_uuid(master_uuid: str) -> Optional[Dict]:
        try:
            conn = _get_connection()
            cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
            cursor.execute(
                "SELECT master_uuid, user_id::text, email, created_at FROM users WHERE master_uuid = %s",
                (master_uuid,),
            )
            row = cursor.fetchone()
            cursor.close()
            conn.close()
            return dict(row) if row else None
        except psycopg2.Error as e:
            logger.error("UserService.get_by_master_uuid failed: %s", e)
            return None

    @staticmethod
    def get_by_user_id(user_id: str) -> Optional[Dict]:
        try:
            conn = _get_connection()
            cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
            cursor.execute(
                "SELECT master_uuid, user_id::text, email, created_at FROM users WHERE user_id = %s::uuid",
                (user_id,),
            )
            row = cursor.fetchone()
            cursor.close()
            conn.close()
            return dict(row) if row else None
        except psycopg2.Error as e:
            logger.error("UserService.get_by_user_id failed: %s", e)
            return None

    @staticmethod
    def get_by_email(email: str) -> Optional[Dict]:
        try:
            conn = _get_connection()
            cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
            cursor.execute(
                "SELECT master_uuid, user_id::text, email, created_at FROM users WHERE email = %s",
                (email,),
            )
            row = cursor.fetchone()
            cursor.close()
            conn.close()
            return dict(row) if row else None
        except psycopg2.Error as e:
            logger.error("UserService.get_by_email failed: %s", e)
            return None


# ============================================================================
# MESSAGE LOG — idempotency & tracking
# ============================================================================

class MessageLog:
    @staticmethod
    def log_message(
        message_id: str,
        message_type: str,
        source: str,
        timestamp: str,
        correlation_id: Optional[str] = None,
        status: str = MessageStatus.RECEIVED.value,
        error_message: Optional[str] = None,
    ) -> bool:
        """Log a message for idempotency. Returns False if duplicate."""
        try:
            conn = _get_connection()
            cursor = conn.cursor()
            cursor.execute(
                """
                INSERT INTO message_log
                    (message_id, message_type, source, timestamp, correlation_id, status, error_message)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """,
                (message_id, message_type, source, timestamp, correlation_id, status, error_message),
            )
            conn.commit()
            cursor.close()
            conn.close()
            logger.info("Message logged | type=%s | id=%s", message_type, message_id)
            return True
        except psycopg2.IntegrityError:
            logger.warning("Duplicate message ignored | id=%s", message_id)
            return False
        except psycopg2.Error as e:
            logger.error("MessageLog.log_message failed: %s", e)
            return False

    @staticmethod
    def update_message_status(
        message_id: str, status: str, error_message: Optional[str] = None
    ) -> bool:
        try:
            conn = _get_connection()
            cursor = conn.cursor()
            cursor.execute(
                """
                UPDATE message_log
                SET status = %s, error_message = %s, processed_at = NOW(), attempts = attempts + 1
                WHERE message_id = %s
                """,
                (status, error_message, message_id),
            )
            conn.commit()
            cursor.close()
            conn.close()
            return True
        except psycopg2.Error as e:
            logger.error("MessageLog.update_message_status failed: %s", e)
            return False

    @staticmethod
    def get_message(message_id: str) -> Optional[Dict]:
        try:
            conn = _get_connection()
            cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
            cursor.execute("SELECT * FROM message_log WHERE message_id = %s", (message_id,))
            row = cursor.fetchone()
            cursor.close()
            conn.close()
            return dict(row) if row else None
        except psycopg2.Error as e:
            logger.error("MessageLog.get_message failed: %s", e)
            return None


# ============================================================================
# SESSIONS
# ============================================================================

class SessionService:
    @staticmethod
    def create_or_update(
        session_id: str,
        title: str,
        start_datetime: str,
        end_datetime: str,
        location: str = "",
        session_type: str = "keynote",
        status: str = "published",
        max_attendees: int = 0,
        current_attendees: int = 0,
        price: Optional[float] = None,
    ) -> bool:
        try:
            conn = _get_connection()
            cursor = conn.cursor()
            cursor.execute(
                """
                INSERT INTO sessions
                    (session_id, title, start_datetime, end_datetime, location,
                     session_type, status, max_attendees, current_attendees, price)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (session_id) DO UPDATE SET
                    title              = EXCLUDED.title,
                    start_datetime     = EXCLUDED.start_datetime,
                    end_datetime       = EXCLUDED.end_datetime,
                    location           = EXCLUDED.location,
                    session_type       = EXCLUDED.session_type,
                    status             = EXCLUDED.status,
                    max_attendees      = EXCLUDED.max_attendees,
                    current_attendees  = EXCLUDED.current_attendees,
                    price              = COALESCE(EXCLUDED.price, sessions.price),
                    updated_at         = NOW(),
                    is_deleted         = FALSE,
                    deleted_at         = NULL
                """,
                (session_id, title, start_datetime, end_datetime, location,
                 session_type, status, max_attendees, current_attendees, price),
            )
            conn.commit()
            cursor.close()
            conn.close()
            logger.info("Session upserted | session_id=%s", session_id)
            return True
        except psycopg2.Error as e:
            logger.error("SessionService.create_or_update failed: %s", e)
            return False

    @staticmethod
    def delete(session_id: str) -> bool:
        """Soft-delete a session."""
        try:
            conn = _get_connection()
            cursor = conn.cursor()
            cursor.execute(
                "UPDATE sessions SET is_deleted = TRUE, deleted_at = NOW(), status = 'deleted' WHERE session_id = %s",
                (session_id,),
            )
            conn.commit()
            cursor.close()
            conn.close()
            logger.info("Session soft-deleted | session_id=%s", session_id)
            return True
        except psycopg2.Error as e:
            logger.error("SessionService.delete failed: %s", e)
            return False

    @staticmethod
    def get(session_id: str, include_deleted: bool = False) -> Optional[Dict]:
        try:
            conn = _get_connection()
            cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
            where = "" if include_deleted else "AND is_deleted = FALSE"
            cursor.execute(
                f"""
                SELECT session_id, title, start_datetime, end_datetime, location,
                       session_type, status, max_attendees, current_attendees, price, created_at, updated_at
                FROM sessions
                WHERE session_id = %s {where}
                """,
                (session_id,),
            )
            row = cursor.fetchone()
            cursor.close()
            conn.close()
            return dict(row) if row else None
        except psycopg2.Error as e:
            logger.error("SessionService.get failed: %s", e)
            return None

    @staticmethod
    def list_all(limit: int = 50, include_deleted: bool = False) -> List[Dict]:
        try:
            conn = _get_connection()
            cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
            where = "" if include_deleted else "WHERE is_deleted = FALSE"
            cursor.execute(
                f"""
                SELECT session_id, title, start_datetime, end_datetime, location,
                       session_type, status, max_attendees, current_attendees, price, created_at, updated_at
                FROM sessions
                {where}
                ORDER BY created_at DESC
                LIMIT %s
                """,
                (limit,),
            )
            rows = cursor.fetchall()
            cursor.close()
            conn.close()
            return [dict(row) for row in rows]
        except psycopg2.Error as e:
            logger.error("SessionService.list_all failed: %s", e)
            return []


# ============================================================================
# SESSION REGISTRATIONS
# user_id column = internal UUID FK → users.user_id (resolved from master_uuid)
# ============================================================================

class SessionRegistrationService:
    @staticmethod
    def register(session_id: str, master_uuid: str) -> bool:
        """Register a user to a session. Resolves master_uuid → internal user_id before writing."""
        try:
            conn = _get_connection()
            cursor = conn.cursor()

            cursor.execute("SELECT user_id FROM users WHERE master_uuid = %s", (master_uuid,))
            row = cursor.fetchone()
            if row is None:
                logger.error("Registration skipped — unknown user | master_uuid=%s", master_uuid)
                cursor.close()
                conn.close()
                return False
            user_id = row[0]

            cursor.execute(
                "INSERT INTO sessions (session_id, title, start_datetime, end_datetime) "
                "VALUES (%s, '', NOW(), NOW()) ON CONFLICT (session_id) DO NOTHING",
                (session_id,),
            )
            cursor.execute(
                """
                INSERT INTO session_registrations (session_id, user_id)
                VALUES (%s, %s)
                ON CONFLICT (session_id, user_id) DO UPDATE SET status = 'confirmed'
                """,
                (session_id, user_id),
            )
            conn.commit()
            cursor.close()
            conn.close()
            logger.info("User registered | session_id=%s | user_id=%s", session_id, user_id)
            return True
        except psycopg2.Error as e:
            logger.error("SessionRegistrationService.register failed: %s", e)
            return False

    @staticmethod
    def cancel(session_id: str, master_uuid: str) -> bool:
        """Cancel a registration. Resolves master_uuid → internal user_id before writing."""
        try:
            conn = _get_connection()
            cursor = conn.cursor()

            cursor.execute("SELECT user_id FROM users WHERE master_uuid = %s", (master_uuid,))
            row = cursor.fetchone()
            if row is None:
                logger.error("Cancellation skipped — unknown user | master_uuid=%s", master_uuid)
                cursor.close()
                conn.close()
                return False
            user_id = row[0]

            cursor.execute(
                "UPDATE session_registrations SET status = 'cancelled' WHERE session_id = %s AND user_id = %s",
                (session_id, user_id),
            )
            conn.commit()
            cursor.close()
            conn.close()
            logger.info("Registration cancelled | session_id=%s | user_id=%s", session_id, user_id)
            return True
        except psycopg2.Error as e:
            logger.error("SessionRegistrationService.cancel failed: %s", e)
            return False

    @staticmethod
    def list_for_session(session_id: str) -> List[Dict]:
        """Return all registrations for a session with user details."""
        try:
            conn = _get_connection()
            cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
            cursor.execute(
                """
                SELECT sr.session_id, sr.user_id::text, u.master_uuid, u.email,
                       sr.registered_at, sr.status
                FROM session_registrations sr
                LEFT JOIN users u ON u.user_id = sr.user_id
                WHERE sr.session_id = %s
                """,
                (session_id,),
            )
            rows = cursor.fetchall()
            cursor.close()
            conn.close()
            return [dict(row) for row in rows]
        except psycopg2.Error as e:
            logger.error("SessionRegistrationService.list_for_session failed: %s", e)
            return []


# ============================================================================
# ICS FEEDS — calendar subscription for non-Outlook users
# user_id column = internal UUID FK → users.user_id (resolved from master_uuid)
# ============================================================================

class IcsFeedService:
    @staticmethod
    def get_or_create(master_uuid: str) -> Optional[Dict]:
        """Get or create an ICS feed token. Resolves master_uuid → internal user_id."""
        try:
            conn = _get_connection()
            cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

            cursor.execute("SELECT user_id FROM users WHERE master_uuid = %s", (master_uuid,))
            row = cursor.fetchone()
            if row is None:
                logger.error("ICS feed skipped — unknown user | master_uuid=%s", master_uuid)
                cursor.close()
                conn.close()
                return None
            user_id = row[0]

            cursor.execute(
                "INSERT INTO ics_feeds (user_id) VALUES (%s) ON CONFLICT (user_id) DO NOTHING",
                (user_id,),
            )
            conn.commit()
            cursor.execute(
                "SELECT user_id::text, feed_token::text FROM ics_feeds WHERE user_id = %s",
                (user_id,),
            )
            row = cursor.fetchone()
            cursor.close()
            conn.close()
            if row:
                logger.info("ICS feed ready | master_uuid=%s | feed_token=%s", master_uuid, row["feed_token"])
            return dict(row) if row else None
        except psycopg2.Error as e:
            logger.error("IcsFeedService.get_or_create failed | master_uuid=%s | error=%s", master_uuid, e)
            return None

    @staticmethod
    def get_master_uuid_by_token(feed_token: str) -> Optional[str]:
        try:
            conn = _get_connection()
            cursor = conn.cursor()
            cursor.execute(
                """
                SELECT u.master_uuid FROM ics_feeds f
                INNER JOIN users u ON u.user_id = f.user_id
                WHERE f.feed_token::text = %s
                """,
                (feed_token,),
            )
            row = cursor.fetchone()
            cursor.close()
            conn.close()
            return row[0] if row else None
        except psycopg2.Error as e:
            logger.error("IcsFeedService.get_master_uuid_by_token failed | error=%s", e)
            return None

    @staticmethod
    def validate_token(master_uuid: str, feed_token: str) -> bool:
        try:
            conn = _get_connection()
            cursor = conn.cursor()
            cursor.execute(
                """
                SELECT 1 FROM ics_feeds f
                INNER JOIN users u ON u.user_id = f.user_id
                WHERE u.master_uuid = %s AND f.feed_token::text = %s
                """,
                (master_uuid, feed_token),
            )
            row = cursor.fetchone()
            cursor.close()
            conn.close()
            return row is not None
        except psycopg2.Error as e:
            logger.error("IcsFeedService.validate_token failed | master_uuid=%s | error=%s", master_uuid, e)
            return False

    @staticmethod
    def get_user_sessions(master_uuid: str) -> List[Dict]:
        """Return all active sessions the user is registered for."""
        try:
            conn = _get_connection()
            cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
            cursor.execute(
                """
                SELECT s.session_id, s.title, s.start_datetime, s.end_datetime, s.location,
                       s.session_type, s.status, s.max_attendees, s.current_attendees, s.price
                FROM sessions s
                INNER JOIN session_registrations sr ON sr.session_id = s.session_id
                INNER JOIN users u ON u.user_id = sr.user_id
                WHERE u.master_uuid = %s
                  AND sr.status = 'confirmed'
                  AND s.is_deleted = FALSE
                ORDER BY s.start_datetime
                """,
                (master_uuid,),
            )
            rows = cursor.fetchall()
            cursor.close()
            conn.close()
            return [dict(row) for row in rows]
        except psycopg2.Error as e:
            logger.error("IcsFeedService.get_user_sessions failed | master_uuid=%s | error=%s", master_uuid, e)
            return []
