-- Migration 008: users table
-- master_uuid = official UUID from Identity Service (received via user.events fanout)
-- user_id     = internal UUID auto-generated by PostgreSQL on insert

CREATE TABLE IF NOT EXISTS users (
    master_uuid TEXT        NOT NULL PRIMARY KEY,
    user_id     UUID        NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    email       TEXT        NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
